### ISSUE TITLE
MUSL and palemoon

### ISSUE THREAD

**Issue by johnny-mac** [Sharrisii/TAZ#5]
Hi, I read that you guys use palemoon w MUSL, can you please show me how you build palemoon? I guess its an 'ebuild' in gentoo? I'm looking for the equivalent of Arch PKGBUILDs / Void templates, sorry I'm not sure what its called. 
I am trying to build palemoon for Void Linux MUSL & could really use some other resources, your help is greatly appreciated, thank you.

**Comment by Sharrisii** [comment]
Hi johnny-mac,
we are currently still working on getting our own gentoo based livecd out, and it won't take that long any more. After that, we'll see whether we can't simply add the musl building option directly into the palemoon github branch, so it would be quite easy then to build it with musl.

**Comment by SJLC** [comment]
Yes, we are interested in submitting some patches upstream, but in the meantime this is our overlay with a gentoo ebuild that builds palemoon with musl

https://github.com/VCTLabs/palemoon-overlay

and you also should take a look at the alpine linux port of palemoon that came before our musl ebuilds (the author @tanertas gave us really helpful advice that helped us get palemoon running solidly on musl) 

https://github.com/tanertas/aports/tree/palemoon/testing/palemoon
